### ISSUE TITLE
add ability to config "default" prefix 

### ISSUE THREAD

**Issue by MishaKav** [noxhsxrk/Jira-to-Git-Branch-Name#1]
First of all, thanks for a simple and great extension.

Can you please add an ability to add default `prefix` in config?
Because in my case, I don't want to add `feature/` or `fix/` or etc before the branch name. I want them clear like `JIRA-1234-your-branch-name-here`
Because now, even if I type enter on the prefix (with empty prefix), it take the default as `feature/`

```json
{
  "jiraToGitBranchName.defaultPrefix": ""
}
```

**Comment by noxhsxrk** [comment]
First of all, I sincerely apologize for the delayed response and any inconvenience it may have caused.

Thank you for your kind words about the extension and for your valuable feedback. Your suggestion to add an ability to configure a default prefix is a great idea. I understand how this feature can improve the flexibility and usability of the extension.

I will implement this feature and let you know once it is available. Thank you for your patience and for contributing to the enhancement of the extension.

**Comment by MishaKav** [comment]
Thank you, another great feature that may be useful is the ability to add a `static` prefix.
In this case, after entering a Jira link, in my clipboard will be the next text: `git checkout -b JIRA-1234-your-branch-name-here`, I may only paste this in the terminal and press the enter button :)

```json
  "jiraToGitBranchName.staticPrefix": "git checkout -b "
```

**Comment by noxhsxrk** [comment]
That's a fantastic suggestion! I've added the ability for users to choose whether they want to copy the generated branch name to the clipboard or directly execute the git checkout -b {branchName} command in the terminal. This way, you can seamlessly integrate your workflow with a static prefix like git checkout -b and paste it directly into the terminal. Plus, I've just published the new version, so you can try it out now! Thanks for the idea—it enhances the extension's flexibility for different Git workflows!
