### ISSUE TITLE
command 'jira-to-git-branch-name.fetchJiraIssue' not found

### ISSUE THREAD

**Issue by MishaKav** [noxhsxrk/Jira-to-Git-Branch-Name#3]
I tried the new version `v0.0.3` but when I chose it from the menu, I got an error. 
I also don't see the new settings that you added.

P.S. The version `v0.02` works fine. 

<img width="278" alt="image" src="https://github.com/user-attachments/assets/4fb92965-6b55-4ad5-8041-794c51f536de">

**Comment by noxhsxrk** [comment]
Thank you for trying out the new version v0.0.3 and for reporting this issue.

I encountered the same problem with new version. The previous version v0.0.2 works fine without any issues.

I am currently working on identifying the cause of this problem and will provide a fix as soon as possible. Your patience and understanding are greatly appreciated.

**Comment by noxhsxrk** [comment]
I’ve attempted several fixes from versions 0.0.3 to 0.0.9, but I still haven’t found a solution. Despite running perfectly fine locally before deployment, issues persist in production. Therefore, I need to deploy each version to test it in the production environment. If you have any suggestions, please let me know.

**Comment by noxhsxrk** [comment]
After several attempts, I decided to switch to npm instead of pnpm, and it worked perfectly.
